### ISSUE TITLE
Performance on mobile/edge devices

### ISSUE THREAD

**Issue by Monoclinic** [huawei-noah/VanillaNet#9]
Hello, thanks for your great work!
I notice that VanillaNet has more channels (512-1024-2048-4096) than traditional deep networks.
As we all know, the bandwidth and computing power of cellphones and some edge devices (for example, Jetson series) are not so sufficient.
However, intuitively a wider network will spend more time on memory access, and the FLOPs of VanillaNet have no advantage on deep networks.
I wonder if you have tried VanillaNet under such conditions and is there any result?

**Comment by HantingChen** [comment]
Thank you for your question! Our aim is to maximize the parallelism of the network and reduce the number of layers as much as possible to achieve better speed on the GPU. The current number of channels represents a good trade-off. Reducing the channels may cause a significant decrease in accuracy with relatively little gain in speed, hence our choice of these specific channel numbers. Of course, you're welcome to try different channel numbers and train the network yourself to explore further.

**Comment by HantingChen** [comment]
Hello, thanks for your question and the recognition of our work! VanillaNet is mainly designed for GPUs with high parallelism, which is why it has a high number of channels, but also a high speed. On edge devices, where the level of parallelism is not as high, VanillaNet might not have an advantage. For these resource-limited devices, we would recommend GhostNet instead. You can find the GhostNet implementation here: https://github.com/huawei-noah/Efficient-AI-Backbones/tree/master/ghostnet_pytorch. Feel free to ask if you have any other questions!

**Comment by Monoclinic** [comment]
Thanks for your kind reply and advice.
